version: "3"

services:
    front_end:
        container_name: "fastapi"
        build:
            context: .
            dockerfile: Dockerfile.yaml
        networks:
            project:
        # ports:
        #     - "8000:8000"
        depends_on:
            back_end:
                condition: service_healthy
            middle_end:
                condition: service_started
        environment:
            - "DATABASE_URL=postgresql://postgres:${YourDbPassword}@back_end:5432/studentdb"
            - "REDIS_URL=redis://middle_end:6379"
            - "POSTGRES_PASSWORD=${YourDbPassword}"
    middle_end:
        container_name: "redis"
        image: redis:7-alpine
        networks:
            project:
    back_end:
        container_name: "database"
        image: postgres:16-alpine
        environment:
            - "POSTGRES_PASSWORD=${YourDbPassword}"
            - "POSTGRES_DB=studentdb"
            - "POSTGRES_USER=postgres"
        networks:
            project:
        healthcheck:
            test: ["CMD-SHELL","pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    proxy:
        container_name: "nginx_reverse_proxy"
        image: nginx:alpine
        networks:
            project:
        ports:
            - "8089:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - front_end
            - middle_end
            - back_end
networks:
    project:
