name: "cicd"

on:
  push:
    branches: CICD

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{secrets.Docker_username}}
          password: ${{secrets.Docker_password}}
      - name: building docker compose
        env:
          YourDbPassword: ${{secrets.mydbpassword}}
        run: "docker compose build"
      - name: Run our build
        run: "docker compose up -d"

      - name: Setup tmate session for SSH access
        uses: mxschmitt/action-tmate@v3